import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
// import { api } from "../../utils/api";
import UserLayout from "../../layout/root";

const UserDashboard: NextPage = () => {
  const { data: sessionData } = useSession();

  if (!sessionData) {
    return <>No session data</>;
  }

  //   if (!secretMessage) {
  //     return <>no secret message</>;
  //   }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserLayout sessionData={sessionData}>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center justify-center gap-4">
            <p className="text-center text-2xl ">
              {sessionData && (
                <span>Logged in as {sessionData.user?.name}</span>
              )}
              {/* {secretMessage && <span> - {secretMessage}</span>
              } */}
            </p>
            <button
              className="rounded-full bg-white/10 px-10 py-3 font-semibold no-underline transition hover:bg-white/20"
              onClick={
                sessionData
                  ? () => void signOut({ callbackUrl: "/" })
                  : () => void signIn()
              }
            >
              {sessionData ? "Sign out" : "Sign in"}
            </button>
          </div>
        </div>
      </UserLayout>
    </>
  );
};

export default UserDashboard;
